{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 2, "total_error": 0}, "tests": {"0": {"status": "FAIL", "message": "   selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//*[@id=\"82195fd0-49b8-4d90-832e-4f73457f5f71\"]/div/section/div/div/div[2]/div/div/div/h1\"}\n     (Session info: chrome=127.0.6533.88); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\n   Stacktrace:\n   #0 0x56615c4ed71a <unknown>\n   #1 0x56615c1be640 <unknown>\n   #2 0x56615c20dc0b <unknown>\n   #3 0x56615c20def1 <unknown>\n   #4 0x56615c251b64 <unknown>\n   #5 0x56615c23090d <unknown>\n   #6 0x56615c24f08a <unknown>\n   #7 0x56615c230683 <unknown>\n   #8 0x56615c200d71 <unknown>\n   #9 0x56615c2017de <unknown>\n   #10 0x56615c4b52ab <unknown>\n   #11 0x56615c4b9242 <unknown>\n   #12 0x56615c4a2665 <unknown>\n   #13 0x56615c4b9dd2 <unknown>\n   #14 0x56615c4872af <unknown>\n   #15 0x56615c4dceb8 <unknown>\n   #16 0x56615c4dd090 <unknown>\n   #17 0x56615c4ec4ec <unknown>\n   #18 0x760240a94ac3 <unknown>\n", "test_name": "test_join_us_loggedOut", "rerun": "0"}, "1": {"status": "FAIL", "message": "   socket.gaierror: [Errno -3] Temporary failure in name resolution\n       urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x7bc508213130>: Failed to resolve 'googlechromelabs.github.io' ([Errno -3] Temporary failure in name resolution)\n       urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='googlechromelabs.github.io', port=443): Max retries exceeded with url: /chrome-for-testing/latest-patch-versions-per-build.json (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7bc508213130>: Failed to resolve 'googlechromelabs.github.io' ([Errno -3] Temporary failure in name resolution)\"))\n       requests.exceptions.ConnectionError: HTTPSConnectionPool(host='googlechromelabs.github.io', port=443): Max retries exceeded with url: /chrome-for-testing/latest-patch-versions-per-build.json (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7bc508213130>: Failed to resolve 'googlechromelabs.github.io' ([Errno -3] Temporary failure in name resolution)\"))\n       requests.exceptions.ConnectionError: Could not reach host. Are you offline?\n", "test_name": "test_join_us_login", "rerun": "0"}}, "suite_name": "test_join_us.py"}}}, "date": "August 02, 2024", "start_time": 1722576121.1523702, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "2", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "2"}