{"content": {"suites": {"0": {"status": {"total_pass": 5, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 2, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_automation_sandbox", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_find_my_candy", "rerun": "0"}, "2": {"status": "PASS", "message": "", "test_name": "test_graveyard_golfing", "rerun": "0"}, "3": {"status": "PASS", "message": "", "test_name": "test_magic_object_model", "rerun": "0"}, "4": {"status": "FAIL", "message": "   selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\"[id=\"popup-widget238491-close-icon\"]\"}\n     (Session info: chrome=127.0.6533.88); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\n   Stacktrace:\n   #0 0x5ef95a38571a <unknown>\n   #1 0x5ef95a056640 <unknown>\n   #2 0x5ef95a0a5c0b <unknown>\n   #3 0x5ef95a0a5ef1 <unknown>\n   #4 0x5ef95a0e9b64 <unknown>\n   #5 0x5ef95a0c890d <unknown>\n   #6 0x5ef95a0e708a <unknown>\n   #7 0x5ef95a0c8683 <unknown>\n   #8 0x5ef95a098d71 <unknown>\n   #9 0x5ef95a0997de <unknown>\n   #10 0x5ef95a34d2ab <unknown>\n   #11 0x5ef95a351242 <unknown>\n   #12 0x5ef95a33a665 <unknown>\n   #13 0x5ef95a351dd2 <unknown>\n   #14 0x5ef95a31f2af <unknown>\n   #15 0x5ef95a374eb8 <unknown>\n   #16 0x5ef95a375090 <unknown>\n   #17 0x5ef95a3844ec <unknown>\n   #18 0x7355f8694ac3 <unknown>\n       AssertionError: something went wrong\n       assert 1 == 0\n", "test_name": "test_packet_publishing", "rerun": "0"}, "5": {"status": "PASS", "message": "", "test_name": "test_sandbox_tool", "rerun": "0"}, "6": {"status": "FAIL", "message": "   socket.gaierror: [Errno -3] Temporary failure in name resolution\n       urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x750211e80b50>: Failed to resolve 'googlechromelabs.github.io' ([Errno -3] Temporary failure in name resolution)\n       urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='googlechromelabs.github.io', port=443): Max retries exceeded with url: /chrome-for-testing/latest-patch-versions-per-build.json (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x750211e80b50>: Failed to resolve 'googlechromelabs.github.io' ([Errno -3] Temporary failure in name resolution)\"))\n       requests.exceptions.ConnectionError: HTTPSConnectionPool(host='googlechromelabs.github.io', port=443): Max retries exceeded with url: /chrome-for-testing/latest-patch-versions-per-build.json (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x750211e80b50>: Failed to resolve 'googlechromelabs.github.io' ([Errno -3] Temporary failure in name resolution)\"))\n       requests.exceptions.ConnectionError: Could not reach host. Are you offline?\n", "test_name": "test_vampire_blog", "rerun": "0"}}, "suite_name": "test_packet_publishing.py"}}}, "date": "August 02, 2024", "start_time": 1722595266.3395033, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "5", "fail": "2", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "7"}